In [1]:
%matplotlib tk
import csv
import sys
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
#from matplotlib.legend_handler import HandlerLine2D

In [2]:
data_matrix_train = []
data_matrix_test = []
with open('prostate.csv','r') as csvfile:
    prostate = csv.reader(csvfile, dialect='excel')
    for row in prostate:
        a = ','.join(row)
        a = a.split('\t')
        if a[10] == 'T':
            data_matrix_train.append(a[1:10])
        else:
            data_matrix_test.append(a[1:10])
data_matrix_train = data_matrix_train
data_matrix_test = data_matrix_test[1:]

print(len(data_matrix_train) , len(data_matrix_test))

67 30


In [3]:
data_train_array = np.array(data_matrix_train, dtype = np.float32)
data_test_array = np.array(data_matrix_test, dtype = np.float32)

In [4]:
data_train_array.shape

(67, 9)

In [5]:
# data_train_array[2,:]

In [6]:
X = data_train_array[:,:8] #8번째 이전 까지 [0~7]
X_T = np.transpose(X)
XX_T = np.dot(X_T,X)

Y = data_train_array[:,8] # 8번째꺼
# print(X.shape, X_T.shape, Y.shape,XX_T.shape,np.linalg.inv(XX_T).shape)

In [7]:
theta = np.dot(np.dot(np.linalg.inv(XX_T), X_T), Y)
theta

array([ 0.5706255 ,  0.6461143 , -0.0180992 ,  0.13833687,  0.7413799 ,
       -0.2068294 ,  0.01197435,  0.00874348], dtype=float32)

In [8]:
# print(np.square(X[:,3]))
# np.sum(np.square(X[:,3]))
# Y.shape
# print(np.delete(X,3,1).shape,np.delete(theta,3,0).shape)

In [9]:
# ydf = Y - np.dot(np.delete(X,3,1),np.delete(theta,3,0))
# print(ydf, ydf.shape)
# print(np.square(X[:,3]))
# print(np.sum(ydf*X[:,3]))

# print(np.sum(np.dot(ydf,X[:,3])))
# ydf.shape

## 여기서부터 computing

매 repeat마다 theta는 이니셜라이즈 해서 람다에 따른 값을 확인하는거야!!!!!!!!

In [10]:
num_theta = len(X[0])
lamb = 15000
#print(num_theta)
coefficients = []
for i in range(10):
    lasso_theta = []
    for d in range(num_theta):
        alpha_d = np.sum(np.square(X[:,d]))
        y_xTtheta = Y - np.dot(np.delete(X,d,1),np.delete(theta,d,0))
        beta_d = np.dot(y_xTtheta ,X[:,d])
        print("beta=",beta_d)
        if beta_d < -lamb:
            theta_d = (beta_d+lamb)/ alpha_d
        elif beta_d > lamb:
            theta_d = (beta_d-lamb)/ alpha_d
        else:
            theta_d=0
        #print(theta_d)
        lasso_theta.append(theta_d)
    lasso_theta=np.array(lasso_theta)
    print(lasso_theta)
    coefficients.append(lasso_theta)
    print("\n")
    lamb = lamb/2.3

print(lamb)
a=np.array(coefficients)
#for x in a:
#    print(x)
#print()
#print(np.sum(np.abs(a),axis=1))
kk = np.sum(np.abs(a), axis=1)
# print(kk)
kk /= kk[-1]
print(a)


plt.plot(kk,a[:,0], marker='o',  label='lcavol')
plt.plot(kk,a[:,1], marker='o',  label='lweight')
plt.plot(kk,a[:,2], marker='o',  label='age')
plt.plot(kk,a[:,3], marker='o',  label='lbph')
plt.plot(kk,a[:,4], marker='o',  label='svi')
plt.plot(kk,a[:,5], marker='o',  label='lcp')
plt.plot(kk,a[:,6], marker='o',  label='gleason')
plt.plot(kk,a[:,7], marker='o',  label='pgg45')
ymin, ymax = plt.ylim()


plt.xlabel('|coef| / max|coef|')
plt.ylabel('Coefficients')
plt.legend()
plt.grid(linestyle ='dotted')
plt.axis('tight')
plt.show()

beta= 124.11138
beta= 578.8904
beta= -5150.6875
beta= 19.60697
beta= 11.120902
beta= -27.419487
beta= 36.754974
beta= 899.72894
[0 0 0 0 0 0 0 0]


beta= 124.11138
beta= 578.8904
beta= -5150.6875
beta= 19.60697
beta= 11.120902
beta= -27.419487
beta= 36.754974
beta= 899.72894
[0 0 0 0 0 0 0 0]


beta= 124.11138
beta= 578.8904
beta= -5150.6875
beta= 19.60697
beta= 11.120902
beta= -27.419487
beta= 36.754974
beta= 899.72894
[ 0.         0.        -0.0081352  0.         0.         0.
  0.         0.       ]


beta= 124.11138
beta= 578.8904
beta= -5150.6875
beta= 19.60697
beta= 11.120902
beta= -27.419487
beta= 36.754974
beta= 899.72894
[ 0.          0.         -0.01376692  0.          0.          0.
  0.          0.        ]


beta= 124.11138
beta= 578.8904
beta= -5150.6875
beta= 19.60697
beta= 11.120902
beta= -27.419487
beta= 36.754974
beta= 899.72894
[ 0.          0.04785047 -0.01621549  0.          0.          0.
  0.          0.0035346 ]


beta= 124.11138
beta= 578.8904
beta= -5150.6875
